---
# use \n for new line and \" for quotes inside quotes
GREETINGS_TEXT: "Добрый день! Вас приветствует компания «ПроГаз»!"
OPTIONS_FIRST_TEXT: "С помощью нашего бота Вы можете посмотреть узнать о нашей компании, уровне добычи газа, а также посмотреть и редактировать информацию по Вашим заказам. Что Вы хотите узнать?"
OPTIONS_FURTHER_TEXT: "Что Вы хотите узнать?"
ABOUT_COMPANY_TEXT: "Мы — крупная газодобывающая компания. Основные направления деятельности — геологоразведка, добыча, транспортировка, хранение, переработка и реализация газа, газового конденсата, реализация газа в качестве моторного топлива, а также производство и сбыт тепло- и электроэнергии.\n «ПроГаз» видит свою миссию в надежном, эффективном и сбалансированном обеспечении потребителей природным газом."
PRODUCTION_LEVEL_TEXT: "В 2022 году «ПроГаз» добыл 412,58 млрд куб. м природного и попутного газа."
ORDERS_TEXT: "Вы можете стать нашим партнером или отследить существующие договорные отношения между нами."

NOT_REALIZED_YET: "Пока не реализовано. Введите \"/start\", чтобы заново вызвать окно диалога."
UNKNOWN_COMMAND: "Неизвестная команда. Введите \"/start\", чтобы вызвать окно диалога."

DB_NAME: "database"
CONTRACT_STATUSES: ["Active", "Finished", "Paused"]
...